#!/usr/bin/env bash
# Build a self-contained `.deb` for clickcast: a venv staged under
# /opt/clickcast, symlinked to /usr/bin/clickcast, with a postinst caveat
# about Chromium (mirroring the Homebrew formula's `caveats` block).
#
# Usage: scripts/build_deb.sh VERSION [ARCH] [OUT_DIR]
#   VERSION  clickcast version to install from PyPI, e.g. 0.3.0
#   ARCH     Debian architecture tag (default: amd64)
#   OUT_DIR  where to write the .deb (default: dist-deb)
#
# See docs/packaging/apt.md for the full design rationale (why a bundled
# venv instead of a bare `Depends: python3`, why no ffmpeg/chromium deps).
set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "usage: $0 VERSION [ARCH] [OUT_DIR]" >&2
  exit 2
fi

VERSION="$1"
ARCH="${2:-amd64}"
OUT_DIR="${3:-dist-deb}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

PKG_ROOT="$STAGE/pkg"
mkdir -p "$PKG_ROOT/opt/clickcast" "$PKG_ROOT/usr/bin" "$PKG_ROOT/DEBIAN"

echo "==> building venv for clickcast==${VERSION}"
python3 -m venv "$PKG_ROOT/opt/clickcast/venv"
"$PKG_ROOT/opt/clickcast/venv/bin/pip" install --upgrade pip --quiet
"$PKG_ROOT/opt/clickcast/venv/bin/pip" install --quiet "clickcast==${VERSION}"

# `python -m venv` bakes the *build-time* absolute path (this staging
# tmpdir) into every console-script's `#!` shebang -- pip's own generated
# entry-point wrappers (clickcast, playwright, ...) all point at
# "$PKG_ROOT/opt/clickcast/venv/bin/python3" rather than
# "/opt/clickcast/venv/bin/python3", the path the package will actually be
# installed at. Left unfixed, `clickcast` fails with "No such file or
# directory" the moment the .deb is installed anywhere but this build host.
# Rewrite every shebang to the real target path -- this is the standard
# "relocate a venv" fixup and is safe here because the replacement path is
# short (well under the ~127-byte shebang limit) and every script was
# generated by this same build, so the pattern is exact.
echo "==> relocating venv shebangs to /opt/clickcast/venv"
for script in "$PKG_ROOT/opt/clickcast/venv/bin/"*; do
  [ -f "$script" ] || continue
  head -c 2 "$script" | grep -q '^#!' || continue
  sed -i "1s|^#!.*python3\(\.[0-9]*\)\?\$|#!/opt/clickcast/venv/bin/python3|" "$script"
done

echo "==> wiring /usr/bin/clickcast"
ln -s /opt/clickcast/venv/bin/clickcast "$PKG_ROOT/usr/bin/clickcast"

# pip installs wheel contents group-writable (0664/0775); Debian packaging
# convention (and lintian's non-standard-file-perm check) expects
# group/other to be read-only. `chmod go-w` only strips write bits, so
# existing executable bits on scripts/binaries are preserved.
echo "==> normalizing file permissions"
find "$PKG_ROOT" -type d -exec chmod 0755 {} +
find "$PKG_ROOT/opt" -type f -exec chmod go-w {} +

echo "==> rendering DEBIAN/control + DEBIAN/postinst"
python3 "$ROOT_DIR/scripts/apt_package.py" control --version "$VERSION" --arch "$ARCH" \
  > "$PKG_ROOT/DEBIAN/control"
python3 "$ROOT_DIR/scripts/apt_package.py" postinst > "$PKG_ROOT/DEBIAN/postinst"
chmod 0755 "$PKG_ROOT/DEBIAN/postinst"

mkdir -p "$OUT_DIR"
DEB_PATH="$OUT_DIR/clickcast_${VERSION}_${ARCH}.deb"
echo "==> building $DEB_PATH"
dpkg-deb --build --root-owner-group "$PKG_ROOT" "$DEB_PATH"
echo "built $DEB_PATH"
